name: ampower_buzzit_mobile
description: "With this app business owners,managers and key personel would be able to access crucial data on the go in the form of reports, dashboard"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.5.1+9

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.3
  connectivity_plus: ^5.0.2
  crypto: ^3.0.2
  dio: ^5.3.3
  dio_cookie_manager: ^3.1.1
  file_picker: ^8.0.3
  flutter_html: ^3.0.0-alpha.6
  flutter_typeahead: ^5.2.0
  fluttertoast: ^8.2.1
  get_it: ^7.2.0
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: null
  intl: ^0.19.0
  json_table: ^2.0.1
  logger: ^2.0.2+1
  open_filex: ^4.5.0
  path: ^1.8.2
  path_provider: ^2.0.14
  permission_handler: ^11.0.0
  provider: ^6.0.5
  rflutter_alert: ^2.0.7
  shared_preferences: ^2.1.0
  fl_chart:
  image_picker: ^1.0.1
  camera: ^0.10.5+2
  flutter_styled_toast: ^2.2.1
  package_info_plus: ^4.2.0
  flutter_image_compress: ^2.3.0
  jiffy: ^6.3.1
  timeago: ^3.7.0
  flutter_native_splash: ^2.4.1
  flutter_mentions: ^2.0.1
  flutter_upgrade_version: ^1.1.7
  http: ^1.3.0
  share_plus: ^10.1.4

dev_dependencies:
  build_runner:
  build_web_compilers:
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: null
  flutter_lints: ^4.0.0

dependency_overrides:

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/

flutter_launcher_icons:
  image_path: "assets/ampower_buzzit_logo_with_bg.jpg"
  android: true
  ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/ampower_buzzit_logo_with_bg.jpg"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/ampower_buzzit_logo_with_bg.jpg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/ampower_buzzit_logo_with_bg.jpg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/ampower_buzzit_logo_with_bg.jpg"

flutter_native_splash:
  android_12:
  android: false
  ios: false
